name: Manual workflow

on:
    workflow_dispatch:

jobs:
    benchmark_python:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                name: [
                        "ubuntu-py37",
                        "ubuntu-py38",
                        "ubuntu-py39",
                        "ubuntu-py310",
                        "macos-py37",
                        "macos-py38",
                        "macos-py39",
                        "macos-py310",
                        "windows-py37",
                        "windows-py38",
                        "windows-py39",
                        "windows-py310",
                ]

                include:
                    -   name: "ubuntu-py37"
                        python: "3.7"
                        os: ubuntu-latest
                    -   name: "ubuntu-py38"
                        python: "3.8"
                        os: ubuntu-latest
                    -   name: "ubuntu-py39"
                        python: "3.9"
                        os: ubuntu-latest
                    -   name: "ubuntu-py310"
                        python: "3.10"
                        os: ubuntu-latest
                    -   name: "macos-py37"
                        python: "3.7"
                        os: macos-latest
                    -   name: "macos-py38"
                        python: "3.8"
                        os: macos-latest
                    -   name: "macos-py39"
                        python: "3.9"
                        os: macos-latest
                    -   name: "macos-py310"
                        python: "3.10"
                        os: macos-latest
                    -   name: "windows-py37"
                        python: "3.7"
                        os: windows-latest
                    -   name: "windows-py38"
                        python: "3.8"
                        os: windows-latest
                    -   name: "windows-py39"
                        python: "3.9"
                        os: windows-latest
                    -   name: "windows-py310"
                        python: "3.10"
                        os: windows-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python }}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install pyperformance
            -   name: Run Benchmarks
                run: |
                    pyperformance run -b pickle -o data.json
            -   uses: actions/upload-artifact@v3
                with:
                    name: ${{ matrix.name }}
                    path: data.json

    benchmark_pyston:
        runs-on: ubuntu-latest

        steps:
            -   name: Install Pyston 
                run: |
                    git clone https://github.com/pyston/pyston.git
                    cd pyston
                    git submodule update --init pyston/LuaJIT pyston/macrobenchmarks
                    pyston/conda/build_pkgs.sh
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install pyperformance
            -   name: Run Benchmarks
                run: |
                    pyperformance run -p pyston -b pickle -o data.json
            -   uses: actions/upload-artifact@v3
                with:
                    name: ${{ matrix.name }}
                    path: data.json

    comparison:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: ["benchmark_python"]

        steps:
            -   uses: actions/download-artifact@v3
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install pyperformance
            -   name: Compare Benchmarks Ubuntu
                run: >
                    pyperf compare_to 
                    ./ubuntu-py37/data.json 
                    ./ubuntu-py38/data.json
                    ./ubuntu-py39/data.json
                    ./ubuntu-py310/data.json
                    --table
            -   name: Compare Benchmarks MacOS
                run: >
                    pyperf compare_to
                    ./macos-py37/data.json
                    ./macos-py38/data.json
                    ./macos-py39/data.json
                    ./macos-py310/data.json
                    --table
            -   name: Compare Benchmarks Windows
                run: >
                    pyperf compare_to
                    ./windows-py37/data.json
                    ./windows-py38/data.json
                    ./windows-py39/data.json
                    ./windows-py310/data.json
                    --table

